config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help",  to: "static_pages#help"
  get "/about",  to: "static_pages#about"
  get "/contact",  to: "static_pages#contact"

  get "/login",   to: "sessions#new"
  post "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  get "/signup",  to: "users#new"
  post "/signup",  to: "users#create"
  resources :users do
    resources :following, only: [:index]
    resources :followers, only: [:index]
  end
  resources :users
  resources :relationships,  only: [:create, :destroy]
  namespace :admin do
    root "users#index"
    resources :users, only: [:index, :destroy]
    resources :categories do
      resources :words, except: [:index, :show]
    end
    resources :report, only: [:index]
  end
  resources :categories, only: [:index, :show] do
    resources :lessons, only: [:create]
  end
  resources :lessons, only: [:show, :destroy, :update]
  resources :words, only: [:index]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    unless current_user.nil?
      @activities = Activity.feed_activities(current_user.id)
        .order(created_at: :desc).paginate page: params[:page],
          per_page: Settings.home_activities_limit
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide :title, t(:about_title) %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | <%= t :system_name %></title>
  </head>
  <body>
    <h1><%= t :about_title %></h1>
    <p>
      <%= raw t :about_intro %>
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide :title, t(:contact_title) %>
<h1><%= t :contact_title %></h1>
<p>
  <%= raw t :contact_intro%>
  <a href="http://www.railstutorial.org/contact">
  <%= t :contact_intro_link%>
  </a>.
</p>

app/views/static_pages/help.html.erb
<% provide :title, t("help_title") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | <%= t :system_name %></title>
  </head>
  <body>
    <h1><%= t :help_title %></h1>
    <p>
      <%= raw t :help_intro %>
      <a href="http://www.railstutorial.org/help">
      <%= t :help_intro_link_text %>
      </a>
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
    </aside>
    <div class="col-md-8">
      <div class="row btn-action-home">
        <div class="col-md-4 col-md-offset-1">
          <%= link_to t(:words_list_btn), words_path,
            class: "btn btn-success btn-block" %>
        </div>
        <div class="col-md-4 col-md-offset-2">
          <%= link_to t(:lesson_btn), categories_path,
            class: "btn btn-primary btn-block" %>
        </div>
      </div>
      <hr/>
      <%= render "shared/activities", activities: @activities %>
    </div>
  </div>

<% else %>
  <div class="center jumbotron">
    <h1><%= t("greeting") + " " + t("system_name")%></h1>

    <h2>
      <%= raw t :intro%>
      <a href="http://training.framgia.vn/">
        <%= raw t :intro_link_text%>
      </a>
    </h2>

    <%= link_to t(:signupnow), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>