config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help",  to: "static_pages#help"
  get "/about",  to: "static_pages#about"
  get "/contact",  to: "static_pages#contact"

  get "/login",   to: "sessions#new"
  post "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  get "/signup",  to: "users#new"
  post "/signup",  to: "users#create"
  resources :users do
    resources :following, only: [:index]
    resources :followers, only: [:index]
  end
  resources :users
  resources :relationships,  only: [:create, :destroy]
  namespace :admin do
    root "users#index"
    resources :users, only: [:index, :destroy]
    resources :categories do
      resources :words, except: [:index, :show]
    end
    resources :report, only: [:index]
  end
  resources :categories, only: [:index, :show] do
    resources :lessons, only: [:create]
  end
  resources :lessons, only: [:show, :destroy, :update]
  resources :words, only: [:index]
end

app/views/shared/_activities.html.erb
<h3><%= t :activities_title %></h3>
<hr/>

<% if activities.any? %>
  <%= render activities  %>
  <div class="text-center">
    <%= will_paginate activities %>
  </div>
<% else %>
  <%= t :no_activity_found %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if defined?(object) && object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t :error_intro %> <%= pluralize object.errors.count, "error" %>.
    </div>
    <ul>
    <% object.errors.each do |attr, msg| %>
      <li><%= "#{attr.capitalize} #{msg}" %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= user_following_index_path @user %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t :following_text %>
  </a>
  <a href="<%= user_followers_path @user %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t :followers_text %>
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t(:view_my_profile_link), current_user %></span>