config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help",  to: "static_pages#help"
  get "/about",  to: "static_pages#about"
  get "/contact",  to: "static_pages#contact"

  get "/login",   to: "sessions#new"
  post "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  get "/signup",  to: "users#new"
  post "/signup",  to: "users#create"
  resources :users do
    resources :following, only: [:index]
    resources :followers, only: [:index]
  end
  resources :users
  resources :relationships,  only: [:create, :destroy]
  namespace :admin do
    root "users#index"
    resources :users, only: [:index, :destroy]
    resources :categories do
      resources :words, except: [:index, :show]
    end
    resources :report, only: [:index]
  end
  resources :categories, only: [:index, :show] do
    resources :lessons, only: [:create]
  end
  resources :lessons, only: [:show, :destroy, :update]
  resources :words, only: [:index]
end

app/models/category.rb
class Category < ApplicationRecord
  include Rails.application.routes.url_helpers

  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy

  mount_uploader :photo, PhotoUploader
  validates :name, presence: true, length: {maximum: 100},
    uniqueness: {case_sensitive: false}
  validates :description, presence: true, length: {maximum: 255}

  scope :group_by_month, -> start_month, end_month do
    where("date_trunc('month', created_at) <= '#{end_month}' AND
      date_trunc('month', created_at) >= '#{start_month}'")
    .group("to_char(created_at, 'YYYY-MM')")
    .order("to_char_created_at_yyyy_mm ASC")
  end

  def self.search name
    name ? where("lower(name) LIKE ?", "%#{name.downcase}%") : all
  end

  def activity_info
    "#{self.name},#{category_path self}"
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :load_category, except: [:index, :new, :create]
  before_action :verify_category_empty, only: [:destroy]

  def index
    @categories = Category.search(params[:name]).order(name: :desc)
    respond_to do |format|
      format.html {
        @categories = @categories.paginate(page: params[:page],
          per_page: Settings.admin_category_limit)
      }
      format.xlsx do
        render xlsx: "index",
        filename: "categories_#{Time.now.strftime("%Y%m%d%H%M%S")}",
        disposition: "inline"
      end
    end
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t :category_update_success_mess
      redirect_to admin_categories_path
    else
      flash.now[:danger] = t :category_update_fail_mess
      render :edit
    end
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t :create_category_success_mess
      redirect_to admin_categories_path
    else
      flash.now[:danger] = t :create_category_fail_mess
      render :new
    end
  end

  def destroy

    if @category.destroy
      flash[:success] = t :category_delete_success_mess
    else
      flash[:danger] = t :category_delete_fail_mess
    end
    redirect_to admin_categories_path
  end

  def show
    @words = @category.words.order(created_at: :desc)
    respond_to do |format|
      format.html {
        @words = @words.paginate(page: params[:page],
          per_page: Settings.admin_word_limit)
      }
      format.xlsx do
        render xlsx: "category_words",
        filename: "category_#{@category.id}_words_#{Time.now.strftime("%Y%m%d%H%M%S")}",
        disposition: "inline"
      end
    end
  end

  private
  def category_params
    params.require(:category).permit :name, :description, :photo
  end

  def verify_category_empty
    if @category.words.any?
      flash[:danger] = t :category_not_empty, name: @category.name
      redirect_to admin_categories_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :load_category, only: [:show]

  def index
    @categories = Category.search(params[:name]).order(created_at: :desc)
      .paginate page: params[:page], per_page: Settings.user_category_limit
  end

  def show
    @lessons = @category.lessons.learned_by(current_user)
      .paginate page: params[:page], per_page: Settings.category_lesson_limit
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td class="category-name">
    <%= category.name %>
  </td>
  <td class="category-description">
    <%= category.description %>
  </td>
  <td class="category-word-total">
    <%= category.words.size %>
  </td>
  <td class="col-actions text-right">
    <%= link_to admin_category_path(category,format: :xlsx),
      class: "btn btn-info btn-xs" do %>
      <span class="glyphicon glyphicon-download-alt"></span>
      <%= t :download_label %>
    <% end %>
    <%= link_to new_admin_category_word_path(category),
      class: "btn btn-success btn-xs" do %>
      <span class="glyphicon glyphicon-plus-sign"></span>
      <%= t :add_a_word %>
    <% end %>
    <%= link_to [:admin, category], class: "btn btn-info btn-xs" do %>
      <span class="glyphicon glyphicon-eye-open">
      </span> <%= t :details %>
    <% end %>
    <%= link_to [:edit, :admin, category],
      class: "btn btn-default btn-xs" do %>
      <span class="glyphicon glyphicon-edit"></span>
      <%= t :edit_label %>
    <% end %>
    <%= link_to admin_category_path(category), method: :delete,
      class: "btn btn-danger btn-xs", data: {confirm: t(:delete_confirm)} do %>
      <span class="glyphicon glyphicon-remove"></span>
      <%= t :delete_label %>
    <% end %>
  </td>
</tr>

app/views/admin/categories/_category_form.html.erb
<%= form_for [:admin, category] do |f| %>
  <%= render "shared/error_messages", object: category %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :photo %>
    <%= f.file_field :photo, class: "form-control" %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, t(:edit_category_title) %>
<% provide :button_text, t(:update_btn) %>

<h1><%= t :edit_category_title %></h1>
<%= render "category_form", category: @category %>

app/views/admin/categories/index.html.erb
<% provide :title, t(:categories_title) %>
<h1><%= t :categories_title %></h1>
<hr/>

<div class="row">
  <div class="col-md-12">
    <div class="pull-right">
      <%= link_to new_admin_category_path, class: "btn btn-primary" do %>
        <span class="glyphicon glyphicon-plus-sign"></span>
        <%= t :create_new_category_label %>
      <% end %>
    </div>
  </div>
</div>
<br/>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag admin_categories_path, method: :get do %>
      <div class="col-md-9">
        <%= text_field_tag :name, params[:name], class: "form-control" %>
      </div>
      <div class="col-md-3">
        <%= submit_tag t(:search), name: nil, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>
</br >

<% if @categories.any? %>
  <span class="text-primary">
    <%= t "categories_search", count: @categories.size %>
  </span>
  <%= link_to admin_categories_path(format: :xlsx, name: "#{params[:name]}"),
    class: "btn btn-info btn-xs" do %>
  <span class="glyphicon glyphicon-download-alt"></span>
    <%= t :export_excel_btn %>
  <% end %>
  <table class="table table-hover">
    <tr>
      <th><%= t :category_name_label %></th>
      <th><%= t :category_description_label %></th>
      <th><%= t :category_word_total_label %></th>
      <th></th>
    </tr>
    <%= render @categories %>
  </table>
  <div class="text-center">
    <%= will_paginate %>
  </div>
<% else %>
  <%= t :no_category_found %>
<% end %>

app/views/admin/categories/new.html.erb
<% provide :title, t(:new_category) %>
<% provide :button_text, t(:create_category) %>

<h1><%= t :new_category %></h1>
<%= render "category_form", category: @category %>

app/views/admin/categories/show.html.erb
<% provide :title, t(:detail_category_title) %>

<h2><%= @category.name %></h2>
<% if @category.photo.url %>
  <%= image_tag @category.photo.url %>
<% end %>
<h3 class="panel-title"><%= t :description_label %></h3>
<p><%= @category.description %></p>

<div class="row">
  <div class="col-md-12">
    <div class="pull-right">
      <%= link_to new_admin_category_word_path(@category),
        class: "btn btn-primary" do %>
        <span class="glyphicon glyphicon-plus-sign"></span>
        <%= t :add_a_word %>
      <% end %>
    </div>
  </div>
</div>
<br/>

<% if @words.any? %>
  <table class="table table-hover">
    <tr>
      <th><%= t :words %></th>
      <th><%= t :meaning %></th>
      <th></th>
    </tr>
    <%= render @words %>
  </table>
  <div class="text-center">
    <%= will_paginate @words %>
  </div>
<% else %>
  <%= t :no_word_found %>
<% end %>